### ISSUE TITLE
FYI - RarityLib 1.1.2 Breaks Ability to Choose cards in game

### ISSUE THREAD

**Issue by Andy0458** [Tess-y/RarityLib#1]
Reverting to 1.1.1 works.

Using these mods with up to date versions as of 7/3/22

BepInExPack_ROUNDS by BepInEx
BlockForcePatch by willuwontu
BPP by BPP_Team
BSC by BossSloth
CardBarPatch by BossSloth
CardChoiceSpawnUniqueCardPatch by Pykess
CardsPlus by willis81808
CardThemeLib by Root
Classes_Manager_Reborn by Root
CM by XAngelMoonX
CR by XAngelMoonX
DamageIndicators by willis81808
EvenSpreadPatch by willuwontu
ExtraMapObjects by BossSloth
GunProjectileSizePatch by Root
GunUnblockablePatch by Pykess
HDC by HatchetDaddy
ItemShops by willuwontu
KeysCards by Keys
LegRaycastersPatch by Pykess
LobbyImprovements by RoundsModdingCommunity
Map_Embiggener by Pykess
MapsExtended by olavim
MapsPlus by willis81808
MMHook by willis81808
ModdingUtils by Pykess
PCE by Pykess
Performance_Improvements by RoundsModding
Pick_N_Cards by Pykess
PlayerJumpPatch by Pykess
RarityLib by Root
RespawnPatch by willuwontu
Root_Cards by Root
RoundsWithFriends by olavim
SetRounds by Ascyst
TemporaryStatsPatch by Pykess
UnboundLib by willis81808
WillsWackyCards by willuwontu
WillsWackyManagers by willuwontu
WillsWackyMapObjects by willuwontu
ZeroGBulletPatch by TeamDK
ZOMC by Zom_23

**Comment by Tess-y** [comment]
yup, missed a line of code in the card spawn patch while i was updating it. bug should now be fixed with version 1.1.3
